version: '2'
services:
  gaseous-server:
    container_name: gaseous-server
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    restart: unless-stopped
    networks:
      - gaseous
    depends_on:
      - gsdb
    ports:
      - 5198:80
    volumes:
      - gs:/home/gaseous/.gaseous-server
    environment:
      - TZ=Europe/Copenhagen
      - dbhost=gsdb
      - dbuser=root
      - dbpass=gaseous
      - igdbclientid=9wy3eholk6lrmlthnyc8wx6m3cb718
      - igdbclientsecret=8ng5o648e9ois2ov7xt3bi0zonggdy
  gsdb:
    container_name: gsdb
    image: mariadb
    restart: unless-stopped
    networks:
      - gaseous
    volumes:
      - gsdb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=gaseous
      - MARIADB_USER=gaseous
      - MARIADB_PASSWORD=gaseous
networks:
  gaseous:
    driver: bridge
volumes:
  gs:
  gsdb:
